# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build
      run: GOOS=linux GOARCH=amd64 go build -o deployment *.go

    - name: Zip
      run: zip deployment.zip deployment

    - name: Set up Terrform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: "1.1.7"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Terraform init
      run: terraform init
      working-directory: terraform/

    - name: Terraform apply
      run: terraform apply -auto-approve
      working-directory: terraform/
